/// <reference path="../pb_data/types.d.ts" />
migrate(
    (app) => {
        const collection = new Collection({
            type: "base",
            name: "briefings",
            createRule: "@request.auth.id != ''",
            listRule: "@request.auth.id != '' && userId = @request.auth.id",
            viewRule: "@request.auth.id != '' && userId = @request.auth.id",
            updateRule: null,
            deleteRule: null,
            fields: [
                {
                    autogeneratePattern: "[a-z0-9]{15}",
                    hidden: false,
                    id: "text3208210256",
                    max: 15,
                    min: 15,
                    name: "id",
                    pattern: "^[a-z0-9]+$",
                    presentable: false,
                    primaryKey: true,
                    required: true,
                    system: true,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000001",
                    max: 0,
                    min: 0,
                    name: "userId",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000002",
                    max: 0,
                    min: 0,
                    name: "area",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000003",
                    max: 0,
                    min: 0,
                    name: "area_nome",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000004",
                    max: 0,
                    min: 0,
                    name: "subdivisao",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000005",
                    max: 0,
                    min: 0,
                    name: "empresa",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000006",
                    max: 0,
                    min: 0,
                    name: "setor",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000007",
                    max: 0,
                    min: 0,
                    name: "porte",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000008",
                    max: 0,
                    min: 0,
                    name: "problema",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000009",
                    max: 0,
                    min: 0,
                    name: "tentativas",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000010",
                    max: 0,
                    min: 0,
                    name: "objetivo",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1000000011",
                    max: 0,
                    min: 0,
                    name: "preview",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: false,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "select1000000012",
                    maxSelect: 1,
                    name: "status",
                    presentable: false,
                    required: true,
                    system: false,
                    type: "select",
                    values: ["aguardando", "em_desenvolvimento", "entregue"],
                },
                {
                    hidden: false,
                    id: "autodate1000000013",
                    name: "created",
                    onCreate: true,
                    onUpdate: false,
                    presentable: false,
                    system: false,
                    type: "autodate",
                },
                {
                    hidden: false,
                    id: "autodate1000000014",
                    name: "updated",
                    onCreate: true,
                    onUpdate: true,
                    presentable: false,
                    system: false,
                    type: "autodate",
                },
            ],
        });

        app.save(collection);
    },
    (app) => {
        const collection = app.findCollectionByNameOrId("briefings");
        app.delete(collection);
    },
);
