/// <reference path="../pb_data/types.d.ts" />
migrate(
    (app) => {
        const collection = new Collection({
            type: "base",
            name: "consultoria_orders",
            createRule: null,
            listRule: "@request.auth.id != '' && userId = @request.auth.id",
            viewRule: "@request.auth.id != '' && userId = @request.auth.id",
            updateRule: null,
            deleteRule: null,
            fields: [
                {
                    autogeneratePattern: "[a-z0-9]{15}",
                    hidden: false,
                    id: "text3208210256",
                    max: 15,
                    min: 15,
                    name: "id",
                    pattern: "^[a-z0-9]+$",
                    presentable: false,
                    primaryKey: true,
                    required: true,
                    system: true,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1100000001",
                    max: 0,
                    min: 0,
                    name: "userId",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1100000002",
                    max: 0,
                    min: 0,
                    name: "email",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "text1100000003",
                    max: 0,
                    min: 0,
                    name: "product_title",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "number1100000004",
                    max: null,
                    min: 0,
                    name: "amount_in_cents",
                    onlyInt: true,
                    presentable: false,
                    required: true,
                    system: false,
                    type: "number",
                },
                {
                    hidden: false,
                    id: "text1100000005",
                    max: 0,
                    min: 0,
                    name: "stripe_session_id",
                    pattern: "",
                    presentable: false,
                    primaryKey: false,
                    required: true,
                    system: false,
                    type: "text",
                },
                {
                    hidden: false,
                    id: "autodate1100000006",
                    name: "created",
                    onCreate: true,
                    onUpdate: false,
                    presentable: false,
                    system: false,
                    type: "autodate",
                },
                {
                    hidden: false,
                    id: "autodate1100000007",
                    name: "updated",
                    onCreate: true,
                    onUpdate: true,
                    presentable: false,
                    system: false,
                    type: "autodate",
                },
            ],
            indexes: [
                "CREATE UNIQUE INDEX `idx_consultoria_orders_session` ON `consultoria_orders` (`stripe_session_id`)",
            ],
        });

        app.save(collection);
    },
    (app) => {
        const collection = app.findCollectionByNameOrId("consultoria_orders");
        app.delete(collection);
    },
);
